### PR TITLE
Assignment 1

### PR DESCRIPTION
**Pull request by DmytroMozghovyi**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
Logical model, and Code were added
## What did you learn from the changes you have made?
How to create sql requests
## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
--
## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
--
## How were these changes tested?
--
## A reference to a related issue in your repository (if applicable)
--
## Checklist
- [*] I can confirm that my changes are working as intended

### CODE REVIEW

**Review by efantinatti — CHANGES_REQUESTED** [review]
Dear Dionysius Indraatmadja

Session 1:
1 - OK. Heads up with the 'assignmeng-1' feature branch. Please read the assignment guidelines for naming conventin being asked.

Session 2:
2 - WHERE: Q2 - option 1: Mising AND condition.

Session 3:
3 - Temp Table: Q1 - Please review it accoring to the question and requirements. Think about the clauses to create a temporary table.
4 - AGGREGATE: Q2 - Heads up with the question. Check the HAVING comparison against the quesition (interpretation).

Final:
4 - Please review prior merging your feature branch 'assignment-one' to 'main'.

Mark: 26 points.

**Comment by DmytroMozghovyi** [comment]
Hi Ernani,

thank you for your support!

Unfortunately I don't understand what is wrong with my Temp Table section :(
Your comment: "3 - Temp Table: Q1 - Please review it accoring to the question and requirements. Think about the clauses to create a temporary table."
I've checked my query couple of times - it works, I see Vendor with vendor_id = 10 with all necessary information.
Please, advise.
image

Thanks.

**Comment by DmytroMozghovyi** [comment]
I just have removed column names after INSERT INTO new_vendor

**Comment by efantinatti** [comment]
Thanks Dmytro. All good.

**Pull request closed without merging**
